version: "3.8"

services:
    db:
        image: mysql:8.0.32
        container_name: kgaming_db
        domainname: local
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
            MYSQL_USER: ${MYSQL_USER:-symfony}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
        ports:
            - "3336:3306"
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - symfony_app

    app:
        image: kgaming_app
        container_name: kgaming_www
        ports:
            - "8080:80"
        environment:
            DATABASE_URL: mysql://${MYSQL_USER:-user}:${MYSQL_PASSWORD:-pass}@db:3306/${MYSQL_DATABASE:-dbName}?serverVersion=8.0.32&charset=utf8mb4
        networks:
            - symfony_app

volumes:
    db-data:

networks:
    symfony_app: